name: Build and Output Check

on:
  push:
    branches:
      - main
      - assignment

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build FruitBasket/FruitBasket.sln --configuration Release
      - name: Run and check output
        run: |
          output=$(dotnet run --project FruitBasket/FruitBasket/FruitBasket.csproj)
          branch="${GITHUB_REF##*/}"
          if [ "$branch" = "main" ]; then
            expected=$(printf "<expected output for main branch>\n")
          elif [ "$branch" = "assignment" ]; then
            expected=$(printf "<expected output for assignment branch>\n")
          else
            echo "No output check for branch: $branch"
            exit 0
          fi
          if [ "$output" != "$expected" ]; then
            echo "Output did not match expected!"
            echo "Actual:"
            echo "$output"
            echo "Expected:"
            echo "$expected"
            exit 1
          fi
          echo "Output matched expected."

