name: .NET Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore FruitBasket/FruitBasket.sln
    - name: Build
      run: dotnet build FruitBasket/FruitBasket.sln --no-restore
    - name: Run
      run: dotnet run --project FruitBasket/FruitBasket/FruitBasket.csproj